DROP TABLE T2T_STAT_RECRUIT;

CREATE TABLE `T2T_STAT_RECRUIT` (
	`ID`  INT NOT NULL AUTO_INCREMENT,
	`KEYWORD`  VARCHAR(20) NULL COMMENT '关键字' ,
	`NUM`  INT NULL DEFAULT 0 COMMENT '数量' ,
	`LABEL`  VARCHAR(30) NULL COMMENT '抓取的关键语句' ,
	`CREATETIME` DATETIME  COMMENT '创建时间',
	PRIMARY KEY (`ID`)
);


INSERT INTO `T2T_STAT_RECRUIT`(KEYWORD,NUM,LABEL,CREATETIME) VALUES ('java', 187151, '为您找到187151个相关职位',now());


