DROP TABLE T2T_STAT_RECRUIT;
CREATE TABLE `T2T_STAT_RECRUIT` (
	`ID`  INT NOT NULL ,
	`KEYWORD`  VARCHAR(20) NULL COMMENT '关键字' ,
	`NUM`  INT NULL DEFAULT 0 COMMENT '数量' ,
	`LABEL`  VARCHAR(30) NULL COMMENT '抓取的关键语句' ,
	PRIMARY KEY (`ID`)
);

INSERT INTO `T2T_STAT_RECRUIT` VALUES (1, 'java', 187151, '为您找到187151个相关职位');


