INSERT INTO `TOP_HISTORY` VALUES (1, 'Spark', '诞生', 'Spark诞生于AMPLab。', '', '', '2009', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (2, 'Spark', '开源', '开源', NULL, NULL, '2010', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (3, 'Spark', 'Apache孵化器项目。', 'Apache孵化器项目。', NULL, '06', '2013', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (4, 'Spark', 'Apache顶级项目。', 'Apache顶级项目。', NULL, '02', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (5, 'Spark', '大数据公司Cloudera宣称加大Spark框架的投入来取代MapReduce。', '大数据公司Cloudera宣称加大Spark框架的投入来取代MapReduce。', NULL, '02', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (6, 'Spark', '大数据公司MapR投入Spark阵营，Apache Mahout放弃MapReduce，将使用Spark作为计算引擎。', NULL, NULL, '04', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (7, 'Spark', 'Pivotal Hadoop集成Spark全栈。', NULL, NULL, '05', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (8, 'Spark', 'Spark 1.0.0 发布。', NULL, '30', '05', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (9, 'Spark', 'Spark 2014 峰会在旧金山召开。', NULL, NULL, '06', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (10, 'Spark', 'Hive on Spark项目启动', NULL, NULL, '07', '2014', 'e', NULL);
INSERT INTO `TOP_HISTORY` VALUES (11, 'Spark', 'Spark 1.1.1 发布', NULL, '26', '11', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (12, 'Spark', 'Spark 1.2.0 发布', NULL, '18', '12', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (13, 'Spark', 'Spark 1.2.1 发布', 'We are happy to announce the availability of Spark 1.2.1! This is a maintenance release that includes contributions from 69 developers. Spark 1.2.1 includes fixes across several areas of Spark, including the core API, Streaming, PySpark, SQL, GraphX, and ', '09', '02', '2015', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (14, 'Spark', 'Spark 1.3.0 发布', 'We are happy to announce the availability of Spark 1.3.0! Spark 1.3.0 is the third release on the API-compatible 1.X line. It is Spark’s largest release ever, with contributions from 174 developers and more than 1,000 commits!', '13', '03', '2015', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (15, 'Spark', 'Spark 1.2.2 和 1.3.1 发布', 'We are happy to announce the availability of Spark 1.2.2 and Spark 1.3.1! These are both maintenance releases that collectively feature the work of more than 90 developers.', '17', '04', '2015', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (16, 'Spark', 'Spark 0.9.2 发布', 'We are happy to announce the availability of Spark 0.9.2! Apache Spark 0.9.2 is a maintenance release with bug fixes. We recommend all 0.9.x users to upgrade to this stable release. Contributions to this release came from 28 developers.', '23', '07', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (17, 'Spark', 'Spark 1.0.1 发布', NULL, '11', '07', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (18, 'Spark', 'Spark 0.9.1 released', 'We are happy to announce the availability of Spark 0.9.1! Apache Spark 0.9.1 is a maintenance release with bug fixes, performance improvements, better stability with YARN and improved parity of the Scala and Python API. We recommend all 0.9.0 users to upg', '09', '04', '2014', 'v', NULL);
INSERT INTO `TOP_HISTORY` VALUES (19, 'Spark', 'Spark 0.9.0 released', NULL, '02', '02', '2014', 'v', NULL);
