<%@ page pageEncoding="UTF-8"%>
<link rel="icon" href="<%=request.getContextPath()%>/theme/favicon.ico">
<%
    //页面全局使用到的变量
    String path = request.getContextPath();
%>
<link rel="stylesheet" type="text/css" href="<%=path%>/js/plugins/datatable/resources/bootstrap/3/dataTables.bootstrap.css">
<link href="<%=path%>/js/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="<%=path%>/js/plugins/jquery.splitter/css/jquery.splitter.css" rel="stylesheet" />
<link href="<%=path%>/theme/tss/css/splitter.vertical.panel.css" rel="stylesheet" />
<link href="<%=path%>/theme/tss/css/doc.css" rel="stylesheet" />

<link rel="stylesheet" type="text/css" href="<%=path %>/js/plugins/datatable/css/jquery.dataTables.css">
<script type="text/javascript" language="javascript" src="<%=path %>/js/plugins/datatable/js/jquery.js"></script>
<script type="text/javascript" language="javascript" src="<%=path %>/js/plugins/datatable/js/jquery.dataTables.js"></script>
<script type="text/javascript" language="javascript" src="<%=path %>/js/common.js"></script>

<!--tss-hdfs-web-->
<script type="text/javascript" src="<%=path%>/js/plugins/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" language="javascript" src="<%=path%>/js/tss-hdfs.js"></script>
<link rel="stylesheet" type="text/css" href="<%=path%>/theme/tss/css/tss-hdfs.css">	